"Baden-Württembergische Meisterschaft 2010","Qualifikation Jugend"
"Klaus Höger                             ","Hohenzollernstraße 30, 73262 Reichenbach/Fils                                                       ","07153-53156, Fax 07153-958587                     ","klaus.hoeger@t-online.de                          "
"Die Staffelsieger der Verbandsligen I und II steigen direkt in die Radballoberliga auf.             Die jeweils zweit, dritt- und viertplatzierten Mannschaften spielen eine Aufstiegsrunde             um den 3. Aufstiegsplatz. Sollten mehr Mannschaften in die 2. Bundesliga aufsteigen,                 so sind die Mannschaften in der Rangfolge der Aufstiegsspiele Nachrücker in die Oberliga.          Der Termin der Aufstiegsspiele zur Radballoberliga wird noch festgelegt.                            "
